### ISSUE TITLE
Server issue...

### ISSUE THREAD

**Issue by CeloGomesBR** [netflie/whatsapp-cloud-api#156]
Hi,
In my local computer running wamp server it works well.
But in server the error message is:
"Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class Netflie\\WhatsAppCloudApi\\WhatsAppCloudApi"

Could you help me? My PHP version is 8.2 (both, server and localhost)

**Comment by aalbarca** [comment]
Hello,

This error is not the fault of this package.

The error comes from your project code due to misuse of dependency injection.

We can only fix bugs that depend on this package.

For premium support with your code please make a donation to keep this project alive. In exchange you will receive premium support to review your project's code.

You can do it in https://github.com/sponsors/aalbarca

Thanks.
